package.json

Updating to match `go-datastore` version from `go-ipfs@0.4.19-dev`

Bump go-datastore to 3.4.1

---

s3.go

As things stand, if a S3 API call fails for any reason other than `s3.ErrCodeNoSuchKey` the error is simply ignored.
This change simply returns the error for the caller to handle

Don't drop errors

---

Makefile
set-target.sh

1. Don't build with `-i`. It tries to rebuild go packages for some reason.
2. Don't run `go list` in-place. It tries to edit the go mod file.
3. Strip the go path when building.

partially fix build issues

---

docker-compose.yml
s3_test.go

This is a small PR to allow local testing. If you `export LOCAL_S3=true` your tests will run against a local s3 on port 4572. Additionally, it adds a (very) small docker-compose to provide a local s3 for you.

allow local testing of the s3 datastore

---

s3.go
s3_test.go

This PR make sure that `Put` is not able to return `ds.ErrNotFound`, whatever AWS return as error.
I don't think it's actually happening, but at least it make sure that my problem is not here.

make sure Put doesn't return ErrNotFound

---

s3.go

S3 store a "/foo" key as "foo" so we need to trim the leading "/", otherwise nothing is returned, which tend to break a few things in go-ipfs.
The tests were passing because they use `""` and not `"/"`

fix Query badly handling prefix

---

README.md

The current release doesn't actually work with go-ipfs 0.4.22 as it uses a newer version of go-datastore. Instead of playing games with go mod, tell users to checkout a known working branch.

doc: document release branches

---

go.mod
go.sum
s3.go

Per ipfs/go-datastore#140 the Datastore interface is being updated to support asynchronous writes.
This PR should be approved before the above PR is merged. After ipfs/go-datastore#140 is merged then this PR should have its go.mod updated and merged.

Update Datastore Interface

---

s3.go

Adds an AWS credentials provider in the credentials chain. Without it tasks running in ECS/Fargate will have their credentials revoked after a relatively short period of time. 
(A container task can then set `CredentialsEndpoint` to `http://169.254.170.2${REL_PATH}` where `${REL_PATH}` comes from one of the default AWS provided environment variables, e.g. `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI`. See https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-metadata-endpoint.html for details.)

Add credentials endpoint provider, for e.g. ECS/Fargate

---

README.md

This little change will cause it so that the ipfs daemon wont emit small errors like `Error: unknown datastore type: levelds`

Edit piping into file to append, not truncate

---

s3_test.go

Test was failing because s3 buckets cannot contain uppercase letters

chore: fixup tests and ensure go vet and staticcheck pass

---

.github/workflows/go-test-integration.yml
docker-compose.yml
s3_test.go

Skip the test suit when the local S3 flag is not set. This is because,
otherwise the tests will certainly fail as the required config will be
empty. Further work is needed to make tests run both on local and remote
S3. For now skip if local S3 flag is absent.
Setup CI integration tests that stands up a local S3 service and runs all
the tests. Note, this can be optimised by tagging the tests. For now run
all tests as part of integration since unit tests are very small and fast.
Use `minio` instead of `localstack` because only S3 service is needed 
and the latter is over four times bigger when it comes to container size.
Relates to:
- https://github.com/ipfs/go-ds-s3/pull/171
- https://github.com/orgs/ipfs/projects/12#card-58209321

Setup CI integration tests with local S3 instance 

---

Makefile

This is required for plugins to work. It should be enabled by default, but apparently not in all cases.
fixes #213

force enable CGO

---

.github/workflows/plugin-test.yml

I want to replace the download from dist.ipfs.io logic here with a common action(https://github.com/ipfs/download-ipfs-distribution-action) to minimise duplication. This is part of work related to this issue: https://github.com/ipfs/go-ipfs/issues/8511
The workflow passes after the changes introduced by me: https://github.com/ipfs/go-ds-s3/runs/4522771738?check_suite_focus=true

chore: use common ipfs/download-ipfs-distribution-action in plugin-test

---

s3.go

There was one remaining un-wired context.

wire a remaining context

---

README.md

The README is a bit not clear that when bundling the plugin and building a new `go-ipfs` binary, there is no need to install the binary manually.
It took me sometime to understand this and have a working plugin.
This PR adds a small explanation to save users the time of finding this themselves.

clarifies that when bundling, you don't need to install the plugin

---

README.md

While testing the bundling process I realized that instruction in README.md regarding to preload list was indeed wrong (as prognosed in [PR #275](https://github.com/ipfs/go-ds-s3/pull/275/files#r1401898924) ).
What doesn't work:
- `echo -en "\ns3ds github.com/ipfs/go-ds-s3/go-ds-s3-plugin 0" >> plugin/loader/preload_list`
- `echo -en "\ns3ds github.com/ipfs/go-ds-s3 0" >> plugin/loader/preload_list`
What does work:
- `echo -en "\ns3ds github.com/ipfs/go-ds-s3/plugin 0" >> plugin/loader/preload_list`
This PR is related to [issue #273](https://github.com/ipfs/go-ds-s3/issues/273).

fix bundling instruction

---

s3.go

AWS credentials array will have STS Web Identity token provider as the first option if `AWS_ROLE_ARN` and `AWS_WEB_IDENTITY_TOKEN_FILE` are available and non-empty in environment.
One of the common ways to provide S3 (or any AWS related service) access to a pod in EKS is to annotate k8s service account with specified IAM Role. Then AWS Web Identity token gets mounted to the pod and `AWS_ROLE_ARN` and `AWS_WEB_IDENTITY_TOKEN_FILE` environment variables are provided automatically to the pod.
This PR enables use of these credentials.

Implement STS Web Identity Role credentials provider

---

.github/workflows/release.yml

v3 is no longer supported as per https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

chore: update upload-artifact action to v4

---

.github/workflows/release.yml

ubuntu-20.04 is getting deprecated in March - https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes/
ubuntu-latest now points to version 24.04

chore: replace ubuntu-20.04 with ubuntu-latest
